# Generated by Django 2.0.3 on 2018-03-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180314_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', height_field='height_field', upload_to='avatars/', width_field='width_field'),
        ),
    ]
