# Generated by Django 2.0.3 on 2018-03-20 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180319_2118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='UserImage',
        ),
    ]
