# Generated by Django 2.0.3 on 2018-03-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180320_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', upload_to='avatars/'),
        ),
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
