# Generated by Django 2.0.3 on 2018-03-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180322_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='avatars/'),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
