# Generated by Django 2.0.3 on 2018-05-19 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20180519_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.Project'),
        ),
    ]
