# Generated by Django 2.0.3 on 2018-05-19 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.Project'),
        ),
    ]
