# Generated by Django 2.0.3 on 2018-06-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20180512_2137'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='skills',
            field=models.ManyToManyField(to='skills.Skill'),
        ),
    ]
