# Generated by Django 2.0.3 on 2018-05-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20180512_2137'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='skill',
        ),
        migrations.AddField(
            model_name='position',
            name='skill',
            field=models.ManyToManyField(related_name='skills', to='skills.Skill'),
        ),
    ]
