# Generated by Django 2.0.3 on 2018-06-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_position_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='skills',
            field=models.ManyToManyField(default=None, to='skills.Skill'),
        ),
    ]
