# Generated by Django 2.0.3 on 2018-05-27 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180527_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='skill',
            new_name='skills',
        ),
    ]
