# Generated by Django 2.0.3 on 2018-04-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180407_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='timeline',
            field=models.TextField(default=''),
        ),
    ]
