# Generated by Django 2.0.3 on 2018-05-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180527_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='skills',
            field=models.ManyToManyField(to='skills.Skill'),
        ),
    ]
