# Generated by Django 2.0.3 on 2018-06-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_position_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='position',
            name='skills',
        ),
    ]
