# Generated by Django 2.0.3 on 2018-06-03 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20180512_2137'),
        ('projects', '0004_auto_20180603_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='projects',
            field=models.ManyToManyField(to='projects.Project'),
        ),
        migrations.AddField(
            model_name='position',
            name='skills',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='skills.Skill'),
        ),
    ]
