# Generated by Django 2.0.3 on 2018-06-03 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180603_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='skills',
            new_name='skill',
        ),
    ]
