# Generated by Django 2.0.3 on 2018-04-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180413_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='project',
            new_name='projects',
        ),
    ]
