# Generated by Django 2.0.3 on 2018-04-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180415_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.SlugField(max_length=100),
        ),
    ]
