# Generated by Django 2.0.3 on 2018-04-24 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0010_auto_20180424_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='applicant',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
