# Generated by Django 2.0.3 on 2018-05-09 20:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0012_usercompltedproject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCompltedProject',
            new_name='UserCompletedProject',
        ),
    ]
