# Generated by Django 2.0.3 on 2018-05-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20180509_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompletedproject',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
