# Generated by Django 2.0.3 on 2018-05-09 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20180509_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercompletedproject',
            name='description',
        ),
        migrations.AddField(
            model_name='usercompletedproject',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
