# Generated by Django 2.0.3 on 2018-05-12 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20180509_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompletedproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
