# Generated by Django 2.0.3 on 2018-05-15 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20180512_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='applicant',
        ),
    ]
