# Generated by Django 2.0.3 on 2018-05-15 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_remove_position_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='applied',
        ),
    ]
